[github page for ksu classifier](https://github.com/nimroha/ksu_classifier)

In [ ]:
!pip install ksu

Code
This package provides a class KSU(Xs, Ys, metric, [gram, prune, logLevel, n_jobs])

Xs and Ys are the data points and their respective labels as numpy arrays

metric is either a callable to compute the metric or a string that names one of our provided metrics (print KSU.METRICS.keys() for the full list)

gram (optional, default=None) a precomputed gramian matrix, will be calculated if not provided.

prune (optional, default=False) a boolean indicating whether to prune the compressed set or not (Algorithm 2 from Near-optimal sample compression for nearest neighbors)

logLevel (optional, default='CRITICAL') a string indicating the logging level (set to 'INFO' or 'DEBUG' to get more information)

n_jobs (optional, default=1) an integer defining how many cpus to use (scipy logic), pass -1 to use all. For n_jobs below -1, (n_cpus + 1 + n_jobs) are used. Thus for n_jobs = -2, all CPUs but one are used.


KSU provides a method compressData([delta, minCompress, maxCompress, greedy, stride, logLevel, numProcs])

Which selects the subset with the lowest estimated error with confidence 1 - delta. Can take arguments:

delta (optional, default=0.1) confidence for error upper bound

minCompress (optional, default=0.05) minimal compression ratio

maxCompress (optional, default=0.1) maximum compression ratio

greedy (optional, default=True) whether to use greedy or hierarichal strategy for net construction

stride (optional, default=200) how many gammas to skip between each iteration (since similar gammas will produce similar nets)

logLevel (optional, default='CRITICAL') a string indicating the logging level (set to 'INFO' or 'DEBUG' to get more information)

numProcs (optional, default=1) number of processes to use


You can then run getClassifier() which returns a 1-NN Classifer (based on sklearn's K-NN) fitted to the compressed data.

Or, run getCompressedSet() to get the compressed data as a tuple of numpy arrays (compressedXs, compressedYs).

In [ ]:
!git clone --depth=1 https://github.com/nimroha/ksu_classifier.git

Cloning into 'ksu_classifier'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 29 (delta 1), reused 13 (delta 0), pack-reused 0
Unpacking objects: 100% (29/29), done.

In [ ]:
!git clone https://github.com/porat-ah/Nearest-Neighbor-Condensing.git

Cloning into 'Nearest-Neighbor-Condensing'...
remote: Enumerating objects: 95, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 95 (delta 35), reused 79 (delta 23), pack-reused 0
Unpacking objects: 100% (95/95), done.

In [ ]:
import os

In [ ]:
os.chdir("Nearest-Neighbor-Condensing/")

In [ ]:
from NNC import NNC

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.io as po
from sklearn.metrics import pairwise_distances
from sklearn.model_selection import train_test_split , cross_validate
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import VarianceThreshold
import math 
import ipaddress

# Data Importing

In [3]:
df_mal = pd.read_csv("https://mcfp.felk.cvut.cz/publicDatasets/CTU-Malware-Capture-Botnet-1/2013-10-01_capture-win12.netflow.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (5,8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
links = [
         "https://mcfp.felk.cvut.cz/publicDatasets/CTU-Mixed-Capture-2/2015-09-08_mixed",
         "https://mcfp.felk.cvut.cz/publicDatasets/CTU-Mixed-Capture-3/2015-03-19_winnormal",
         "https://mcfp.felk.cvut.cz/publicDatasets/CTU-Mixed-Capture-4/2015-03-19_capture-win",
         "https://mcfp.felk.cvut.cz/publicDatasets/CTU-Mixed-Capture-5/2015-03-19_winnormal"
         ]

In [5]:
before = []
after = []
for l in links:
  after.append(pd.read_csv(l + ".binetflow.after.infection"))
  before.append(pd.read_csv(l + ".binetflow.before.infection"))

In [6]:
df_nor = pd.read_csv("https://mcfp.felk.cvut.cz/publicDatasets/CTU-Normal-5/2015-06-09_normal.binetflow")

In [7]:
df_nor_labeled = pd.read_csv("https://mcfp.felk.cvut.cz/publicDatasets/CTU-Normal-7/2013-12-17_capture1.binetflow.labeled")

In [8]:
df_mal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5422750 entries, 0 to 5422749
Data columns (total 14 columns):
 #   Column     Dtype
---  ------     -----
 0   StartTime  object
 1   Dur        float64
 2   Label      object
 3   Proto      object
 4   SrcAddr    object
 5   Sport      object
 6   Dir        object
 7   DstAddr    object
 8   Dport      object
 9   State      object
 10  sTos       float64
 11  dTos       float64
 12  TotPkts    int64
 13  TotBytes   int64
dtypes: float64(3), int64(2), object(9)
memory usage: 579.2+ MB

In [9]:
df_mal.head()

,StartTime,Dur,Label,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes
0,1970/01/01 01:00:00.000000,0.000000,flow=Background,llc,00:00:00:00:00:00,0,->,00:00:00:00:00:00,0,INT,NaN,NaN,1,60
1,1970/01/01 01:00:06.684086,3.003788,flow=Background,udp,fe80::1daf:d1a3:4b5:ff61,546,->,ff02::1:2,547,INT,0.0,NaN,3,441
2,1970/01/01 01:00:06.733573,2.003445,flow=Background-ARP,arp,0.0.0.0,NaN,who,10.0.2.112,NaN,INT,NaN,NaN,3,126
3,1970/01/01 01:00:06.733703,0.000000,flow=Background,ipv6-icmp,::,135,->,ff02::1:ffb5:ff61,0,NNS,0.0,NaN,1,78
4,1970/01/01 01:00:06.733755,4.005612,flow=Background,ipv6-icmp,fe80::1daf:d1a3:4b5:ff61,133,->,ff02::2,0,NRS,0.0,NaN,2,140

# Data Preprocessing

In [10]:
dfs = after + before +[df_nor , df_nor_labeled , df_mal]

In [11]:
col_inter = set(df_mal.columns).intersection(*[set(df.columns) for df in dfs])

In [12]:
col_inter

{'Dir',
 'Dport',
 'DstAddr',
 'Dur',
 'Label',
 'Proto',
 'Sport',
 'SrcAddr',
 'StartTime',
 'State',
 'TotBytes',
 'TotPkts',
 'dTos',
 'sTos'}

In [13]:
for df in dfs:
  df.drop([c for c in df if not c in col_inter ], axis= 1, inplace = True )

In [14]:
# https://www.tutorialsbuddy.com/convert-ip-to-integer-and-integer-to-ip-in-python
def ip_to_integer(string_ip):
    try:
        if type(ipaddress.ip_address(string_ip)) is ipaddress.IPv4Address:
            return int(ipaddress.IPv4Address(string_ip))
        if type(ipaddress.ip_address(string_ip)) is ipaddress.IPv6Address:
            return int(ipaddress.IPv6Address(string_ip))
    except Exception as e:
        return -1

def ip_to_num(string_ip):
  ip_num = ip_to_integer(string_ip)
  try:
    return math.log2(ip_num)
  except:
    return ip_num

In [15]:
def port_to_num(port):
  try:
    return int(port)
  except:
    return int(port , 16)

In [16]:
for df in dfs:
  df.SrcAddr = df.SrcAddr.apply(ip_to_num)
  df.DstAddr = df.DstAddr.apply(ip_to_num)
  df.Sport = df.Sport.fillna(-1).apply(port_to_num)
  df.Dport = df.Dport.fillna(-1).apply(port_to_num)

In [34]:
all_states = pd.Series(list(set(df_mal.State).union(*[set(df.State) for df in dfs])))

In [45]:
all_states = all_states.dropna().apply(lambda x : x.strip()).unique()

In [79]:
vals , keys = pd.factorize(all_states)
all_states_map = dict(zip(keys, vals))

In [47]:
all_dirs = pd.Series(list(set(df_mal.Dir).union(*[set(df.Dir) for df in dfs])))

In [48]:
all_dirs = all_dirs.dropna().apply(lambda x : x.strip()).unique()

In [80]:
vals , keys = pd.factorize(all_dirs)
all_dirs_map = dict(zip(keys, vals))

In [49]:
all_protocols = pd.Series(list(set(df_mal.Proto).union(*[set(df.Proto) for df in dfs])))

In [50]:
all_protocols = all_protocols.dropna().apply(lambda x : x.strip()).unique()

In [81]:
vals , keys = pd.factorize(all_protocols)
all_protocols_map = dict(zip(keys, vals))

In [71]:
def mapping(x , _map):
  try:
    x = x.strip()
    return _map[x]
  except:
    return -1

In [85]:
for df in dfs:
  df.State = df.State.apply(lambda x: mapping(x , all_states_map))
  df.Dir = df.Dir.apply(lambda x: mapping(x , all_dirs_map))
  df.Proto = df.Proto.apply(lambda x: mapping(x , all_protocols_map))

In [88]:
for df in dfs:
  df.drop(['StartTime'] , axis = 1 , inplace = True )